

all: RSbook.pdf RSbookNEW.pdf

RSbook.pdf:  RSbook.tex \
		   Cover.tex Includes/Includes.tex \
		   Prologue.tex Infra1.tex Infra2.tex
	pdflatex RSbook.tex


RSbookNEW.pdf:  RSbookNEW.tex \
		   Cover.tex Includes/Includes.tex \
		   Prologue.tex Infra1NEW.tex Infra2.tex
	pdflatex RSbookNEW.tex
